[project]
name = "text-to-speech"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "kokoro>=0.9.4",
    "langchain-core>=1.5.1",
    "langchain-ollama>=1.1.0",
    "numpy>=2.5.1",
    "soundfile>=0.14.0",
    "uvicorn",
]

[dependency-groups]
dev = [
    "httpx",
    "pytest",
]
